from datetime import datetime
from sqlmodel import Field, Session, SQLModel, UniqueConstraint, create_engine, select
from main import app
# class Post(SQLModel, table=True):

#     #UUID generated by database. DO NOT DECLARE
#     post_id: int | None = Field(default=None, primary_key=True)
#     user_id: int = Field(foreign_key="user.user_id")
#     content: str | None